apiVersion: v1
kind: Service
metadata:
  name: bookshelf-frontend
  labels:
    app: bookshelf
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: bookshelf
    tier: frontend
